version: '3.9'

services:
  user-db:
    networks:
      - microapps
    container_name: userdb_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - user-db:/data/db
  
  order-db:
    networks:
      - microapps
    container_name: orderdb_container
    restart: always
    image: mongo:latest
    ports:
      - 2718:27017
    volumes:
      - order-db:/data/db
  
  product-db:
    networks:
      - microapps
    container_name: productdb_container
    restart: always
    image: mongo:latest
    ports:
      - 2719:27017
    volumes:
      - product-db:/data/db

  user-service:
    networks:
      - microapps
    container_name: user-service_container
    build: ./users
    restart: always
    depends_on:
      - service-registry
      - user-db
      - gateway-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=service-registry
      - HOSTNAME=user-service
      - PORT=8080
      - DB_URI=mongodb://user-db:27017/Microservices-users
      - SECRET_KEY=NCJNSJXXDKSDD
  
  order-service:
    networks:
      - microapps
    container_name: order-service_container
    build: ./order
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - service-registry
      - order-db
      - gateway-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=service-registry
      - HOSTNAME=order-service
      - PORT=8081
      - DB_URI=mongodb://order-db:27017/Microservices-orders
      - SECRET_KEY=NCJNSJXXDKSDD
  
  product-service:
    networks:
      - microapps
    container_name: product-service_container
    build: ./product
    restart: always
    ports:    
      - 8082:8082
    depends_on:
      - product-db
      - gateway-service
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=service-registry
      - HOSTNAME=product-service
      - PORT=8082
      - DB_URI=mongodb://product-db:27017/Microservices-product
      - ADMIN_SECRET_KEY=jbcdiojldqskndINIRE

  admin-service:
    depends_on:
      - service-registry
    networks:
      - microapps
    container_name: admin-service_container
    build: ./admin
    restart: always
    ports:
      - 8085:8085
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=service-registry
      - HOSTNAME=admin-service
      - PORT=8085
      - ADMIN_SECRET_KEY=jbcdiojldqskndINIRE

  gateway-service:
    depends_on:
      - service-registry
    container_name: gateway-service_container
    build: ./apiGateway
    restart: always
    ports:
      - 9001:9001
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=service-registry
      - HOSTNAME=gateway-service
      - PORT=9001
      - SECRET_KEY=NCJNSJXXDKSDD
      - HOSTNAME_1=user-service
      - HOSTNAME_2=order-service
      - HOSTNAME_3=product-service
      - HOSTNAME_4=admin-service
    networks:
      - microapps

  service-registry:
    image: steeltoeoss/eureka-server
    ports:
      - 8761:8761
    networks:
      - microapps

networks:
  microapps:

volumes:
  product-db: {}
  order-db: {}
  user-db: {}
